// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzhaicqvntxcsxmkyobk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6aGFpY3F2bnR4Y3N4bWt5b2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODMyOTQsImV4cCI6MjA2ODA1OTI5NH0.assz4bP_WUKwLn--SLdVWBpNMCnDPO2DEc0ut8QZ_1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});